<?php
/**
 * Generated by Protobuf protoc plugin.
 */


namespace ProtobufCompilerTest\Protos\Service;

/**
 * Protobuf service : SearchService
 */
interface SearchService
{

    /**
     * @param \ProtobufCompilerTest\Protos\Service\SearchRequest $input
     * @return \ProtobufCompilerTest\Protos\Service\SearchResponse
     */
    public function search(\ProtobufCompilerTest\Protos\Service\SearchRequest $input);

}

