<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : php_options.proto
 */


namespace ProtobufCompilerTest\Protos\Options\ParentMessage\InnerMessage;

/**
 * Protobuf enum :
 * ProtobufCompilerTest.Protos.ParentMessage.InnerMessage.InnerMessageEnum
 */
class InnerMessageEnum extends \Protobuf\Enum
{

    /**
     * VALUE = 0
     */
    const VALUE_VALUE = 0;

    /**
     * @var \ProtobufCompilerTest\Protos\Options\ParentMessage\InnerMessage\InnerMessageEnum
     */
    protected static $VALUE = null;

    /**
     * @return \ProtobufCompilerTest\Protos\Options\ParentMessage\InnerMessage\InnerMessageEnum
     */
    public static function VALUE()
    {
        if (self::$VALUE !== null) {
            return self::$VALUE;
        }

        return self::$VALUE = new self('VALUE', self::VALUE_VALUE);
    }

    /**
     * @param int $value
     * @return \ProtobufCompilerTest\Protos\Options\ParentMessage\InnerMessage\InnerMessageEnum
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::VALUE();
            default: return null;
        }
    }


}

