<?php
/**
 * Generated by Protobuf protoc plugin.
 */


namespace ProtobufCompilerTest\Protos\Person;

/**
 * Protobuf enum : PhoneType
 */
class PhoneType extends \Protobuf\Enum
{

    /**
     * MOBILE = 0
     */
    const MOBILE_VALUE = 0;

    /**
     * HOME = 1
     */
    const HOME_VALUE = 1;

    /**
     * WORK = 2
     */
    const WORK_VALUE = 2;

    /**
     * @var \ProtobufCompilerTest\Protos\Person\PhoneType
     */
    protected static $MOBILE = null;

    /**
     * @var \ProtobufCompilerTest\Protos\Person\PhoneType
     */
    protected static $HOME = null;

    /**
     * @var \ProtobufCompilerTest\Protos\Person\PhoneType
     */
    protected static $WORK = null;

    /**
     * @return \ProtobufCompilerTest\Protos\Person\PhoneType
     */
    public static function MOBILE()
    {
        if (self::$MOBILE !== null) {
            return self::$MOBILE;
        }

        return self::$MOBILE = new \ProtobufCompilerTest\Protos\Person\PhoneType('MOBILE', self::MOBILE_VALUE);
    }

    /**
     * @return \ProtobufCompilerTest\Protos\Person\PhoneType
     */
    public static function HOME()
    {
        if (self::$HOME !== null) {
            return self::$HOME;
        }

        return self::$HOME = new \ProtobufCompilerTest\Protos\Person\PhoneType('HOME', self::HOME_VALUE);
    }

    /**
     * @return \ProtobufCompilerTest\Protos\Person\PhoneType
     */
    public static function WORK()
    {
        if (self::$WORK !== null) {
            return self::$WORK;
        }

        return self::$WORK = new \ProtobufCompilerTest\Protos\Person\PhoneType('WORK', self::WORK_VALUE);
    }

    /**
     * @param int $value
     * @return \ProtobufCompilerTest\Protos\Person\PhoneType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::MOBILE();
            case 1: return self::HOME();
            case 2: return self::WORK();
            default: return null;
        }
    }


}

