<?php
/**
 * Generated by Protobuf protoc plugin.
 */


namespace ProtobufCompilerTest\Protos;

/**
 * Protobuf message : Person
 *
 * @\Protobuf\Annotation\Descriptor(
 *   name="Person",
 *   package="ProtobufCompilerTest.Protos",
 *   fields={
 *     @\Protobuf\Annotation\Field(
 *       name="name",
 *       tag=1,
 *       type=9,
 *       label=2
 *     ),
 *     @\Protobuf\Annotation\Field(
 *       name="id",
 *       tag=2,
 *       type=5,
 *       label=2
 *     ),
 *     @\Protobuf\Annotation\Field(
 *       name="email",
 *       tag=3,
 *       type=9,
 *       label=1
 *     ),
 *     @\Protobuf\Annotation\Field(
 *       name="phone",
 *       tag=4,
 *       type=11,
 *       label=3,
 *       reference="ProtobufTest.Protos.Person.PhoneNumber"
 *     )
 *   }
 * )
 */
class Person extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * name required string = 1
     *
     * @var string
     */
    protected $name = null;

    /**
     * id required int32 = 2
     *
     * @var int
     */
    protected $id = null;

    /**
     * email optional string = 3
     *
     * @var string
     */
    protected $email = null;

    /**
     * phone repeated message = 4
     *
     * @var \Doctrine\Common\Collections\Collection<"\ProtobufTest\Protos\Person\PhoneNumber">
     */
    protected $phone = null;

    /**
     * Check if 'name' has a value
     *
     * @return bool
     */
    public function hasName()
    {
        return $this->name !== null;
    }

    /**
     * Get 'name' value
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set 'name' value
     *
     * @param string $value
     */
    public function setName($value)
    {
        return $this->name = $value;
    }

    /**
     * Check if 'id' has a value
     *
     * @return bool
     */
    public function hasId()
    {
        return $this->id !== null;
    }

    /**
     * Get 'id' value
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set 'id' value
     *
     * @param int $value
     */
    public function setId($value)
    {
        return $this->id = $value;
    }

    /**
     * Check if 'email' has a value
     *
     * @return bool
     */
    public function hasEmail()
    {
        return $this->email !== null;
    }

    /**
     * Get 'email' value
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set 'email' value
     *
     * @param string $value
     */
    public function setEmail($value)
    {
        return $this->email = $value;
    }

    /**
     * Check if 'phone' has a value
     *
     * @return bool
     */
    public function hasPhoneList()
    {
        return $this->phone !== null;
    }

    /**
     * Get 'phone' value
     *
     * @return \Doctrine\Common\Collections\Collection<"\ProtobufTest\Protos\Person\PhoneNumber">
     */
    public function getPhoneList()
    {
        return $this->phone;
    }

    /**
     * Set 'phone' value
     *
     * @param \Doctrine\Common\Collections\Collection<"\ProtobufTest\Protos\Person\PhoneNumber"> $value
     */
    public function setPhoneList(\Doctrine\Common\Collections\Collection $value)
    {
        return $this->phone = $value;
    }

    /**
     * Add a new element to 'phone'
     *
     * @param \ProtobufTest\Protos\Person\PhoneNumber $value
     */
    public function addPhone(\ProtobufTest\Protos\Person\PhoneNumber $value)
    {
        $this->phone[] = $value;
    }

    /**
     * Get unknown values
     *
     * @return Protobuf\UnknownFieldSet
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->name !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->name);
        }

        if ($this->id !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->id);
        }

        if ($this->email !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->email);
        }

        if ($this->phone !== null) {
            foreach ($this->phone as $val) {
                $innerSize = $val->serializedSize($context);

                $size += 1;
                $size += $innerSize;
                $size += $calculator->computeVarintSize($innerSize);
            }
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->name = $reader->readString($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->id = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->email = $reader->readString($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \ProtobufTest\Protos\Person\PhoneNumber();

                if ($this->phone === null) {
                    $this->phone = new \Protobuf\MessageCollection();
                }

                $this->phone->add($innerMessage);

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->name === null) {
            throw new \UnexpectedValueException('Field "\\ProtobufCompilerTest\\Protos\\Person#name" (tag 1) is required but has no value.');
        }

        if ($this->id === null) {
            throw new \UnexpectedValueException('Field "\\ProtobufCompilerTest\\Protos\\Person#id" (tag 2) is required but has no value.');
        }

        if ($this->name !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeString($stream, $this->name);
        }

        if ($this->id !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->id);
        }

        if ($this->email !== null) {
            $writer->writeVarint($stream, 26);
            $writer->writeString($stream, $this->email);
        }

        if ($this->phone !== null) {
            foreach ($this->phone as $val) {
                $writer->writeVarint($stream, 34);
                $writer->writeVarint($stream, $val->serializedSize($sizeContext));
                $val->writeTo($context);
            }
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = new \Protobuf\ReadContext($stream, $config->getStreamReader());
        $message = new \ProtobufCompilerTest\Protos\Person();

        $message->readFrom($context);

        return $message;
    }


}

