<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : addressbook.proto
 */


namespace ProtobufCompilerTest\Protos;

/**
 * Protobuf message : ProtobufCompilerTest.Protos.PhoneNumber
 *
 * @\Protobuf\Annotation\Descriptor(
 *   name="PhoneNumber",
 *   package="ProtobufCompilerTest.Protos",
 *   fields={
 *     @\Protobuf\Annotation\Field(
 *       name="number",
 *       tag=1,
 *       type=9,
 *       label=2
 *     ),
 *     @\Protobuf\Annotation\Field(
 *       name="type",
 *       tag=2,
 *       type=14,
 *       label=1,
 *       default="HOME",
 *       reference="ProtobufCompilerTest.Protos.PhoneType"
 *     )
 *   },
 *   extensions={
 *   }
 * )
 */
class PhoneNumber extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * number required string = 1
     *
     * @var string
     */
    protected $number = null;

    /**
     * type optional enum = 2
     *
     * @var \ProtobufCompilerTest\Protos\PhoneType
     */
    protected $type = null;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->type = \ProtobufCompilerTest\Protos\PhoneType::HOME();
    }

    /**
     * Check if 'number' has a value
     *
     * @return bool
     */
    public function hasNumber()
    {
        return $this->number !== null;
    }

    /**
     * Get 'number' value
     *
     * @return string
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Set 'number' value
     *
     * @param string $value
     */
    public function setNumber($value)
    {
        return $this->number = $value;
    }

    /**
     * Check if 'type' has a value
     *
     * @return bool
     */
    public function hasType()
    {
        return $this->type !== null;
    }

    /**
     * Get 'type' value
     *
     * @return \ProtobufCompilerTest\Protos\PhoneType
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set 'type' value
     *
     * @param \ProtobufCompilerTest\Protos\PhoneType $value
     */
    public function setType(\ProtobufCompilerTest\Protos\PhoneType $value)
    {
        return $this->type = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createReadContext($stream);
        $message = new self();

        $message->readFrom($context);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->number === null) {
            throw new \UnexpectedValueException('Field "\\ProtobufCompilerTest\\Protos\\PhoneNumber#number" (tag 1) is required but has no value.');
        }

        if ($this->number !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeString($stream, $this->number);
        }

        if ($this->type !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->type->value());
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->number = $reader->readString($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->type = \ProtobufCompilerTest\Protos\PhoneType::valueOf($reader->readVarint($stream));

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->put($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->number !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->number);
        }

        if ($this->type !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->type->value());
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }


}

